const employees = [
  {
    employee_id: 100,
    first_name: "Steven",
    last_name: "King",
    age: 24,
    email: "steven.king@sqltutorial.org",
    phone_number: "515.123.4567",
    hire_date: "1987-06-17",
    job_id: 4,
    salary: "24000.00",
    manager_id: null,
    department_id: 9,
    employees_images: [
      {
        epim_id: 27,
        epim_filename: "after order.jpg",
        epim_path: "/uploads/after order.jpg",
        epim_primary: false,
        epim_employee_id: 100,
      },
      {
        epim_id: 26,
        epim_filename: "cangkir jadul.jpg",
        epim_path: "/uploads/cangkir jadul.jpg",
        epim_primary: false,
        epim_employee_id: 100,
      },
    ],
  },
  {
    employee_id: 152,
    first_name: "Dodo",
    last_name: "Ronald",
    age: 34,
    email: "ronaldo17@gmail.com",
    phone_number: "0812-9999-0213",
    hire_date: "2011-12-03",
    job_id: 4,
    salary: "53500.00",
    manager_id: null,
    department_id: 3,
    employees_images: [
      {
        epim_id: 27,
        epim_filename: "after order.jpg",
        epim_path: "/uploads/after order.jpg",
        epim_primary: false,
        epim_employee_id: 100,
      },
      {
        epim_id: 26,
        epim_filename: "cangkir jadul.jpg",
        epim_path: "/uploads/cangkir jadul.jpg",
        epim_primary: false,
        epim_employee_id: 100,
      },
    ],
  },
  {
    employee_id: 152,
    first_name: "Rayhan",
    last_name: "Buto",
    age: 28,
    email: "butoanak99@gmail.com",
    phone_number: "0812-9999-0213",
    hire_date: "1998-03-18",
    job_id: 4,
    salary: "10000.00",
    manager_id: null,
    department_id: 3,
    employees_images: [
      {
        epim_id: 27,
        epim_filename: "after order.jpg",
        epim_path: "/uploads/after order.jpg",
        epim_primary: false,
        epim_employee_id: 100,
      },
      {
        epim_id: 26,
        epim_filename: "cangkir jadul.jpg",
        epim_path: "/uploads/cangkir jadul.jpg",
        epim_primary: false,
        epim_employee_id: 100,
      },
    ],
  },
  {
    employee_id: 152,
    first_name: "Saul",
    last_name: "Agus",
    age: 44,
    email: "lemonade@gmail.com",
    phone_number: "0812-9999-0213",
    hire_date: "1995-07-21",
    job_id: 3,
    salary: "22000.00",
    manager_id: null,
    department_id: 9,
    employees_images: [
      {
        epim_id: 27,
        epim_filename: "after order.jpg",
        epim_path: "/uploads/after order.jpg",
        epim_primary: false,
        epim_employee_id: 100,
      },
      {
        epim_id: 26,
        epim_filename: "cangkir jadul.jpg",
        epim_path: "/uploads/cangkir jadul.jpg",
        epim_primary: false,
        epim_employee_id: 100,
      },
    ],
  },
  {
    employee_id: 152,
    first_name: "Roida",
    last_name: "Hamonangan",
    age: 31,
    email: "lemonade@gmail.com",
    phone_number: "0812-9999-0213",
    hire_date: "1994-09-09",
    job_id: 4,
    salary: "22000.00",
    manager_id: null,
    department_id: 9,
    employees_images: [
      {
        epim_id: 27,
        epim_filename: "after order.jpg",
        epim_path: "/uploads/after order.jpg",
        epim_primary: false,
        epim_employee_id: 100,
      },
      {
        epim_id: 26,
        epim_filename: "cangkir jadul.jpg",
        epim_path: "/uploads/cangkir jadul.jpg",
        epim_primary: false,
        epim_employee_id: 100,
      },
    ],
  },
];

module.exports = employees;
