const employees = [
  {
    employee_id: 100,
    first_name: "Steven",
    last_name: "King",
    email: "steven.king@sqltutorial.org",
    phone_number: "515.123.4567",
    hire_date: "1987-06-17",
    job_id: 4,
    salary: "24000.00",
    manager_id: null,
    department_id: 9,
    employees_images: [
      {
        epim_id: 27,
        epim_filename: "after order.jpg",
        epim_path: "/uploads/after order.jpg",
        epim_primary: false,
        epim_employee_id: 100,
      },
      {
        epim_id: 26,
        epim_filename: "cangkir jadul.jpg",
        epim_path: "/uploads/cangkir jadul.jpg",
        epim_primary: false,
        epim_employee_id: 100,
      },
    ],
  },
  {
    employee_id: 152,
    first_name: "Dodo",
    last_name: "Ronald",
    email: "ronaldo17@gmail.com",
    phone_number: "0812-9999-0213",
    hire_date: "2001-06-17",
    job_id: 4,
    salary: "53500.00",
    manager_id: null,
    department_id: 3,
    employees_images: [
      {
        epim_id: 27,
        epim_filename: "after order.jpg",
        epim_path: "/uploads/after order.jpg",
        epim_primary: false,
        epim_employee_id: 100,
      },
      {
        epim_id: 26,
        epim_filename: "cangkir jadul.jpg",
        epim_path: "/uploads/cangkir jadul.jpg",
        epim_primary: false,
        epim_employee_id: 100,
      },
    ],
  },
  {
    employee_id: 152,
    first_name: "Rayhan",
    last_name: "Buto",
    email: "butoanak99@gmail.com",
    phone_number: "0812-9999-0213",
    hire_date: "2001-06-17",
    job_id: 4,
    salary: "10000.00",
    manager_id: null,
    department_id: 3,
    employees_images: [
      {
        epim_id: 27,
        epim_filename: "after order.jpg",
        epim_path: "/uploads/after order.jpg",
        epim_primary: false,
        epim_employee_id: 100,
      },
      {
        epim_id: 26,
        epim_filename: "cangkir jadul.jpg",
        epim_path: "/uploads/cangkir jadul.jpg",
        epim_primary: false,
        epim_employee_id: 100,
      },
    ],
  },
  {
    employee_id: 152,
    first_name: "Saul",
    last_name: "Lemon",
    email: "lemonade@gmail.com",
    phone_number: "0812-9999-0213",
    hire_date: "2001-06-17",
    job_id: 3,
    salary: "22000.00",
    manager_id: null,
    department_id: 9,
    employees_images: [
      {
        epim_id: 27,
        epim_filename: "after order.jpg",
        epim_path: "/uploads/after order.jpg",
        epim_primary: false,
        epim_employee_id: 100,
      },
      {
        epim_id: 26,
        epim_filename: "cangkir jadul.jpg",
        epim_path: "/uploads/cangkir jadul.jpg",
        epim_primary: false,
        epim_employee_id: 100,
      },
    ],
  },
  {
    employee_id: 152,
    first_name: "Roida",
    last_name: "Hamonangan",
    email: "lemonade@gmail.com",
    phone_number: "0812-9999-0213",
    hire_date: "2001-06-17",
    job_id: 4,
    salary: "22000.00",
    manager_id: null,
    department_id: 9,
    employees_images: [
      {
        epim_id: 27,
        epim_filename: "after order.jpg",
        epim_path: "/uploads/after order.jpg",
        epim_primary: false,
        epim_employee_id: 100,
      },
      {
        epim_id: 26,
        epim_filename: "cangkir jadul.jpg",
        epim_path: "/uploads/cangkir jadul.jpg",
        epim_primary: false,
        epim_employee_id: 100,
      },
    ],
  },
];

module.exports = employees;
